### ISSUE TITLE
iOS & macOS help

### ISSUE THREAD

**Issue by vhugogarcia** [yiszza/Material.Components.Maui#3]
First, I would like to THANK YOU for this amazing repository. This is HUGE help because, if we have apps following Material You guidelines, this will help a lot to all of us as developers.

I downloaded the repository and noticed on the README.md that you are asking for help with iOS and macOS, I downloaded it locally on macOS and tried to compile it for macOS or iOS by adding the _net7.0-ios;net7.0-maccatalyst_ to the .csproj file and I keep getting 4 errors that is preventing to run the sample app locally on iOS.

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1047398/212120961-6c2bca3f-302d-4dee-96ae-07a385c60934.png">

I believe you can find what our friend @jsuarezruiz did on his repository as experimental. Maybe even @jsuarezruiz can come here and provide some insights to solve the issue we are facing on iOS and macOS.

https://github.com/dotnet/Microsoft.Maui.Graphics.Controls

**Comment by vhugogarcia** [comment]
Thanks @yiszza for the help. I will pull latest changes and run tests locally and share the findings here 😎👍🏻

**Comment by yiszza** [comment]
Bad news?

**Comment by vhugogarcia** [comment]
I am unable to run it until I implement the SplitViewer on macOS and iOS. However, I am still researching best practices to achieve that. 

btw, I ran it on Android and it looks just wonderful. You did an amazing work

**Comment by yiszza** [comment]
In fact, the controls marked as `😭needs help` in the readme usually indicate that they need to work with navite controls, which is why they need help, because I can't build and test them on the ios/mac platform.
You need to create a new project, test the controls marked as `😄ready` and `🤔unverified` on the mac/ios platform, if they perform well and think they are valuable, you can help improve controls marked as `😭needs help` or anything.

Thank you agin!👍🏻

**Comment by vhugogarcia** [comment]
I'm closing this issue, since I was able to compile the project and collaborate with feedback on the compatibility for iOS and macOS 👍🏻 .

Thanks @yiszza for the support again.
